export const elements = {
  todayLabel: document.querySelector("#today-label"),
  todayCount: document.querySelector("#today-count"),
  upcomingCount: document.querySelector("#upcoming-count"),
  completedCount: document.querySelector("#completed-count"),
  totalCount: document.querySelector("#total-count"),
  resultCount: document.querySelector("#result-count"),
  list: document.querySelector("#appointment-list"),
  search: document.querySelector("#search-input"),
  filters: document.querySelector("#filter-group"),

  dataMenu: document.querySelector("#data-menu"),
  dataMenuButton: document.querySelector("#data-menu-button"),
  dataMenuPanel: document.querySelector("#data-menu-panel"),
  storageNote: document.querySelector("#storage-note"),
  importInput: document.querySelector("#import-input"),

  dialog: document.querySelector("#appointment-dialog"),
  form: document.querySelector("#appointment-form"),
  dialogTitle: document.querySelector("#dialog-title"),
  clientName: document.querySelector("#client-name"),
  service: document.querySelector("#service"),
  customService: document.querySelector("#custom-service"),
  customServiceField: document.querySelector("#custom-service-field"),
  date: document.querySelector("#appointment-date"),
  time: document.querySelector("#appointment-time"),
  description: document.querySelector("#description"),
  completedToggle: document.querySelector("#completed-toggle"),
  imageInput: document.querySelector("#images"),
  imageCount: document.querySelector("#image-count"),
  imagePreviews: document.querySelector("#image-previews"),
  error: document.querySelector("#form-error"),
  save: document.querySelector("#save-appointment"),
  closeDialog: document.querySelector("#close-dialog"),
  cancelDialog: document.querySelector("#cancel-dialog"),

  confirmDialog: document.querySelector("#confirm-dialog"),
  confirmTitle: document.querySelector("#confirm-title"),
  confirmMessage: document.querySelector("#confirm-message"),
  confirmAccept: document.querySelector("#confirm-accept"),
  confirmCancel: document.querySelector("#confirm-cancel"),

  lightbox: document.querySelector("#lightbox"),
  lightboxImage: document.querySelector("#lightbox-image"),
  lightboxCaption: document.querySelector("#lightbox-caption"),
  lightboxClose: document.querySelector("#lightbox-close"),
  lightboxPrev: document.querySelector("#lightbox-prev"),
  lightboxNext: document.querySelector("#lightbox-next"),

  toastStack: document.querySelector("#toast-stack"),
  newAppointment: document.querySelector("#new-appointment"),
};
